services:
  chromium:
    image: linuxserver/chromium:${wizard_base:-latest}
    container_name: chromium
    environment:
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
      - TZ=Asia/Shanghai
      - LC_ALL=zh_CN.UTF-8
      - CUSTOM_USER=${wizard_username:-admin}
      - PASSWORD=${wizard_password:-admin}
      - SUBFOLDER=${wizard_base_path:-/chromium/}
      # - CHROME_CLI=http://localhost/
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /var/apps/fn-chromium/shares/chromium/config:/config
    ports:
      - ${wizard_port:-4000}:3000
      # - ${wizard_port:-4001}:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - trim-default
networks:
  trim-default:
    external: true
